epochs: 20
time_step: 4
layer: 1
dim: 49
num_heads: 1
patch_size: 7
mlp_ratio: 4
start_epoch: 10
data_dir: /Volumes/export/isn/keli/code/data
dataset: torch/mnist
resume: ./output/train/20231019-143201-spikformer-28/checkpoint-10.pth.tar
num_classes: 10
img_size: 28
input_size: [1, 28, 28]
mean: [0.445]
std: [0.269]
mixup: 0.5
mixup_off_epoch: 200
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0

reprob: 0.25
remode: const
amp: True
batch_size: 32
val_batch_size: 32
lr: 1e-3
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
cooldown_epochs: 1
warmup_epochs: 2
warmup_lr: 0.001
opt: adamw
smoothing: 0.1
workers: 1